name: FreeRDP
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://github.com/thorrevenge/test-rdp/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/thorrevenge/test-rdp/blob/main/start.bat?raw=true -OutFile start.bat
        Invoke-WebRequest https://github.com/thorrevenge/test-rdp/blob/main/wallpaper.jpg?raw=true -OutFile wallpaper.jpg
        Invoke-WebRequest https://github.com/thorrevenge/test-rdp/blob/main/wallpaper.bat?raw=true -OutFile wallpaper.bat
        Invoke-WebRequest https://github.com/thorrevenge/test-rdp/blob/main/winrar.zip?raw=true -OutFile winrar.exe
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip

    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy winrar.exe C:\Users\Public\Desktop\winrar.exe
        copy wallpaper.jpg C:\Users\Public\Desktop\wallpaper.jpg
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
      
    - name: Connecting to your RDP.
      run: cmd /c start.bat
      
    - name: Install Winrar
      run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s
      
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://github.com/thorrevenge/test-rdp/blob/main/loop.ps1?raw=true -OutFile loop.ps1
        ./loop.ps1
